config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'searches#show'

  namespace :admin do
    resources :railway_stations do
      member do
        patch :position
        patch :time
      end
    end

    resources :trains do
      resources :carriages, shallow: true, except: :index
    end

    resources :routes
    resource :resource, only: :show
  end

  resources :tickets, shallow: true
  resource :search, only: [:show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  has_many :trains, foreign_key: :current_station_id

  validates :title, presence: true

  scope :ordered, -> { select('railway_stations.*, railway_stations_routes.position').joins(:railway_stations_routes).order('railway_stations_routes.position').distinct }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def update_time(route, arrival_time, departure_time)
    station_route = station_route(route)
    station_route.update(arrival_time: arrival_time, departure_time: departure_time) if station_route
  end

  def position_in(route)
    station_route(route).try(:position)
  end

  def arrival_time_in(route)
    station_route = station_route(route)
    station_route.arrival_time.strftime('%H:%M') if station_route && station_route.arrival_time.present?
  end

  def departure_time_in(route)
    station_route = station_route(route)
    station_route.departure_time.strftime('%H:%M') if station_route && station_route.departure_time.present?
  end

  private

  def station_route(route)
    @station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/controllers/admin/railway_stations_controller.rb
class Admin::RailwayStationsController < Admin::BaseController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :position, :time]
  before_action :set_route, only: [:position, :time]

  def index
    @railway_stations = RailwayStation.all
  end

  def show; end

  def new
    @railway_station = RailwayStation.new
  end

  def edit; end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to admin_railway_station_path(@railway_station)
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to admin_railway_station_path(@railway_station)
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to admin_railway_stations_url
  end

  def position
    @railway_station.update_position(@route, params[:position].to_i)
    redirect_to admin_route_path(@route)
  end

  def time
    @railway_station.update_time(@route, params[:arrival_time], params[:departure_time])
    redirect_to admin_route_path(@route)
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:title)
  end

  def set_route
    @route = Route.find(params[:route_id])
  end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/admin/railway_stations/_form.html.erb
<div class="row">
  <%= form_for([:admin, railway_station], html: { class: 'form-horizontal col-sm-6', role: 'form' }) do |f| %>
    <% if railway_station.errors.any? %>
      <div id="error_explanation">
        <h2><%= t('common.errors') %></h2>

        <ul>
        <% railway_station.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, class: 'col-sm-3 control-label' %>
      <%= f.text_field :title, class: 'col-sm-3 form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit "#{@railway_station.new_record? ? t('common.create') : t('common.update')}", class: 'form-control' %>
    </div>
  <% end %>
</div>

app/views/admin/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.title %></td>
  <td><%= link_to t('common.show'), admin_railway_station_path(railway_station) %></td>
  <td><%= link_to t('common.edit'), edit_admin_railway_station_path(railway_station) %></td>
  <td><%= link_to t('common.delete'), admin_railway_station_path(railway_station), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/railway_stations/edit.html.erb
<h3><%= t('.title') %></h3>

<%= render 'form', railway_station: @railway_station %>

<%= link_to t('common.show'), admin_railway_station_path(@railway_station), class: 'btn btn-primary' %> |
<%= link_to t('common.back'), admin_railway_stations_path, class: 'btn btn-primary' %>

app/views/admin/railway_stations/index.html.erb
<h3><%= t('.title') %></h3>

<table class='table table-hover'>
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to t('.new_station'), new_admin_railway_station_path, class: 'btn btn-primary' %>

app/views/admin/railway_stations/new.html.erb
<h3><%= t('.title') %></h3>
<%= render 'form', railway_station: @railway_station %>
<%= link_to t('common.back'), admin_railway_stations_path, class: 'btn btn-primary' %>

app/views/admin/railway_stations/show.html.erb
<p>
  <strong><%= t('.station_name_title') %>:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to t('common.edit'), edit_admin_railway_station_path(@railway_station), class: 'btn btn-primary' %> |
<%= link_to t('common.back'), admin_railway_stations_path, class: 'btn btn-primary' %>