config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'searches#show'

  namespace :admin do
    resources :railway_stations do
      member do
        patch :position
        patch :time
      end
    end

    resources :trains do
      resources :carriages, shallow: true, except: :index
    end

    resources :routes
    resource :resource, only: :show
  end

  resources :tickets, shallow: true
  resource :search, only: [:show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  private

  def set_name
    self.name = if self.persisted?
      "#{railway_stations.ordered.first.title} - #{railway_stations.ordered.last.title}" 
    else
      "#{railway_stations.first.title} - #{railway_stations.last.title}"
    end
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, 'Маршрут должен иметь как минимум две станции!')
    end
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to admin_route_path(@route)
    else
      render :new
    end

  end

  def edit; end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/admin/routes/_edit_name_form.html.erb
<%= form_for [:admin, route], html: { style: "display: none" } do |f| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('common.errors') %></h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: 'sr-only' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit t('common.update') %>
  </div>
<% end %>

app/views/admin/routes/_form.html.erb
<div class="row">
  <%= form_for([:admin, route], html: { class: 'form-horizontal col-sm-6', role: 'form' }) do |f| %>
    <% if route.errors.any? %>
      <div id="error_explanation">
        <h2><%= t('common.errors') %></h2>
        <ul>
        <% route.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-3 control-label' %>
      <%= f.text_field :name, readonly: true, class: 'col-sm-3 form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :railway_station_ids, class: 'col-sm-3 control-label' %>
      <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true, class: 'col-sm-3 form-control' } %>
    </div>

    <div class="form-group">
      <%= f.submit "#{@route.new_record? ? t('common.create') : t('common.update')}", class: 'form-control' %>
    </div>
  <% end %>
</div>

app/views/admin/routes/_route.html.erb
<tr>
  <td>
    <div id="route_name_<%= route.id %>">
      <%= route.name %>
    </div>
    <%= render 'edit_name_form', route: route %>
  </td>
  <td><%= route.trains.size %></td>
  <td><%= link_to t('common.show'), admin_route_path(route) %></td>
  <td><%= link_to t('common.edit'), '', class: 'edit_route', data: { route_id: route.id } %></td>
  <td><%= link_to t('common.delete'), admin_route_path(route), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/routes/edit.html.erb
<h3><%= t('.title') %></h3>
<%= render 'form', route: @route %>
<%= link_to t('common.show'), admin_route_path(@route), class: 'btn btn-primary' %> |
<%= link_to t('common.back'), admin_routes_path, class: 'btn btn-primary' %>

app/views/admin/routes/index.html.erb
<h3><%= t('.title') %></h3>
<table class='table table-hover'>
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.trains_count') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @routes %>
  </tbody>
</table>
<br>
<%= link_to t('.new_route'), new_admin_route_path, class: 'btn btn-primary' %>

app/views/admin/routes/new.html.erb
<h3><%= t('.title') %></h3>
<%= render 'form', route: @route %>
<%= link_to t('common.back'), admin_routes_path, class: 'btn btn-primary' %>

app/views/admin/routes/show.html.erb
<p>
  <strong><%= t('.route_name_title') %>:</strong>
  <%= @route.name %>
</p>

<% if @route.trains.present? %>
  <table>
    <caption><strong><%= t('.trains_on_route') %></strong></caption>
    <thead>
      <tr>
        <th><%= t('.train_number_title') %></th>
        <th><%= t('.train_route_title') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%= render @route.trains %>
    </tbody>
  </table>
<% else %>
  <strong><%= t('.no_trains_on_route') %></strong>
<% end %>
<br />
<% if @route.railway_stations.present? %>
  <table>
    <caption><strong><%= t('.station_on_route') %></strong></caption>
    <thead>
      <tr>
        <th><%= t('.route_name_title') %></th>
        <th><%= t('.route_position_title') %></th>
        <th><%= t('.route_departure_arrival_title') %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @route.railway_stations.ordered.each do |railway_station| %>
        <tr>
          <td><%= railway_station.title %></td>
          <td>
            <%= form_tag(position_admin_railway_station_path(railway_station), method: :patch) do %>
              <%= text_field_tag(:position, railway_station.position_in(@route)) %>
              <%= hidden_field_tag(:route_id, @route.id) %>
              <%= submit_tag t('.save_station_position_button') %>
            <% end %>
          </td>
          <td>
            <%= form_tag(time_admin_railway_station_path(railway_station), method: :patch) do %>
              <%= time_field_tag(:arrival_time, railway_station.arrival_time_in(@route)) %>
              <%= time_field_tag(:departure_time, railway_station.departure_time_in(@route)) %>
              <%= hidden_field_tag(:route_id, @route.id) %>
              <%= submit_tag t('.save_time_button') %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <strong><%= t('.no_stations_on_route') %></strong>
<% end %>
<br />
<%= link_to t('common.edit'), edit_admin_route_path(@route), class: 'btn btn-primary' %> |
<%= link_to t('common.back'), admin_routes_path, class: 'btn btn-primary' %>