config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'searches#show'

  namespace :admin do
    resources :railway_stations do
      member do
        patch :position
        patch :time
      end
    end

    resources :trains do
      resources :carriages, shallow: true, except: :index
    end

    resources :routes
    resource :resource, only: :show
  end

  resources :tickets, shallow: true
  resource :search, only: [:show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :finish_station, class_name: 'RailwayStation', foreign_key: :finish_station_id
  belongs_to :user

  scope :find_tickets, ->(user) { user.admin? ? all : where(user: user) }

  after_create :send_notification_about_buy_ticket
  after_destroy :send_notification_about_delete_ticket

  def route_name
    "#{start_station.title} - #{finish_station.title}"
  end

  private

  def send_notification_about_buy_ticket
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def send_notification_about_delete_ticket
    TicketsMailer.delete_ticket(self.user, self).deliver_now
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin, only: [:edit, :update]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:show, :destroy]

  def index
    @tickets = Ticket.find_tickets(current_user)
  end

  def show; end

  def new
    @train = Train.find(params[:train_id])
    @start_station = RailwayStation.find(params[:start_station_id])
    @finish_station = RailwayStation.find(params[:finish_station_id])
    @ticket = @train.tickets.new
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)

    if @ticket.save
      redirect_to @ticket
    else
      render :new
    end
  end

  def edit; end

  def update
    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:first_name, :last_name, :second_name, :passport_number, :start_station_id, :finish_station_id, :train_id)
  end

  def check_admin
    redirect_to tickets_path, alert: 'У вас нет прав на это действие!' unless current_user.admin?
  end

  def check_owner
    redirect_to tickets_path, alert: 'У вас нет прав на это действие!' unless  current_user.admin? || @ticket.user == current_user
  end
end

app/views/tickets/_ticket.html.erb
<tr>
  <td><%= ticket.train.number %></td>
  <td><%= ticket.train.route.name %></td>
  <td><%= ticket.first_name %></td>
  <td><%= ticket.user.email %></td>
  <td><%= link_to t('common.show'), ticket_path(ticket) %></td>
  <% if current_user.admin? %>
    <td><%= link_to t('common.edit'), edit_ticket_path(ticket) %></td>
  <% end %>
  <td><%= link_to t('common.delete'), ticket_path(ticket), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/tickets/edit.html.erb
<div class="row">
  <h1>Изменение билета</h1>

  <%= form_for(@ticket, html: { class: 'form-horizontal col-sm-6', role: 'form' }) do |f| %>
    <% if @ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= t('common.errors') %></h2>
        <ul>
        <% @ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :first_name, class: 'col-sm-3 control-label' %>
      <%= f.text_field :first_name, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: 'col-sm-3 control-label' %>
      <%= f.text_field :last_name, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :second_name, class: 'col-sm-3 control-label' %>
      <%= f.text_field :second_name, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :passport_number, class: 'col-sm-3 control-label' %>
      <%= f.text_field :passport_number, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :start_station, class: 'col-sm-3 control-label' %>
      <%= f.collection_select :start_station_id, RailwayStation.all, :id, :title, {}, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :finish_station, class: 'col-sm-3 control-label' %>
      <%= f.collection_select :finish_station_id, RailwayStation.all, :id, :title, {}, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :train, class: 'col-sm-3 control-label' %>
      <%= f.collection_select :train_id, Train.all, :id, :number, {}, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit t('common.update'), class: 'form-control' %>
    </div>
  <% end %>
</div>
<%= link_to t('common.show'), ticket_path(@ticket), class: 'btn btn-primary' %> |
<%= link_to t('common.back'), tickets_path, class: 'btn btn-primary' %>

app/views/tickets/index.html.erb
<h3><%= t('.title') %></h3>

<table class='table table-hover'>
  <thead>
    <tr>
      <th><%= t('.train_number_title') %></th>
      <th><%= t('.train_route_title') %></th>
      <th><%= t('.passenger_title') %></th>
      <th><%= t('.buyer_title') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @tickets %>
  </tbody>
</table>

<br>

<%= link_to t('common.back'), search_path, class: 'btn btn-primary' %>

app/views/tickets/new.html.erb
<div class="row">
  <h1><%= t('.title') %></h1>
  <%= form_for(@ticket, html: { class: 'form-horizontal col-sm-6', role: 'form' }) do |f| %>
    <% if @ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= t('common.errors') %></h2>
        <ul>
        <% @ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :first_name, class: 'col-sm-3 control-label' %>
      <%= f.text_field :first_name, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: 'col-sm-3 control-label' %>
      <%= f.text_field :last_name, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :second_name, class: 'col-sm-3 control-label' %>
      <%= f.text_field :second_name, class: 'col-sm-3 form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :passport_number, class: 'col-sm-3 control-label' %>
      <%= f.text_field :passport_number, class: 'col-sm-3 form-control' %>
    </div>
    <%= f.hidden_field :start_station_id, value: @start_station.id %>
    <%= f.hidden_field :finish_station_id, value: @finish_station.id %>
    <%= f.hidden_field :train_id, value: @train.id %>
    <div class="form-group">
      <%= f.submit t('common.create'), class: 'form-control' %>
    </div>
  <% end %>
</div>
<%= link_to t('common.back'), search_path, class: 'btn btn-primary' %>

app/views/tickets/show.html.erb
<p>
  <strong>Поезд:</strong>
  <strong><%= t('.train_number') %></strong>
  <%= @ticket.train.number %>
</p>
<p>
  <strong>Маршрут:</strong>
  <%= @ticket.train.route.name %>
</p>
<p>
  <strong>Отправление из:</strong>
  <%= @ticket.start_station.title %>
</p>
<p>
  <strong>Прибытие в:</strong>
  <%= @ticket.finish_station.title %>
</p>
<p>
  <strong>Фамилия:</strong>
  <%= @ticket.first_name %>
</p>
<p>
  <strong>Имя:</strong>
  <%= @ticket.last_name %>
</p>
<p>
  <strong>Отчество:</strong>
  <%= @ticket.second_name %>
</p>
<p>
  <strong>Номер паспорта:</strong>
  <%= @ticket.passport_number %>
</p>
<p>
  <strong>Покупатель</strong>
  <%= @ticket.user.email %>
</p>

<%= link_to 'Назад', search_path, class: 'btn btn-primary' %>