config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'searches#show'

  namespace :admin do
    resources :railway_stations do
      member do
        patch :position
        patch :time
      end
    end

    resources :trains do
      resources :carriages, shallow: true, except: :index
    end

    resources :routes
    resource :resource, only: :show
  end

  resources :tickets, shallow: true
  resource :search, only: [:show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route, optional: true
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, optional: true
  has_many :carriages
  has_many :tickets

  validates :number, presence: true

  delegate :economy_count, to: :carriages
  delegate :business_count, to: :carriages
  delegate :coupe_count, to: :carriages
  delegate :seat_count, to: :carriages
  delegate :economy, to: :carriages
  delegate :coupe, to: :carriages
  delegate :business, to: :carriages
  delegate :seat, to: :carriages
  delegate :top_seats, to: :carriages
  delegate :bottom_seats, to: :carriages
  delegate :side_top_seats, to: :carriages
  delegate :side_bottom_seats, to: :carriages
  delegate :seats, to: :carriages

  def seats_count(carriage_type, seats_type)
    carriages.where(type: carriage_type).sum(seats_type)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show; end

  def new
    @train = Train.new
  end

  def edit; end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to admin_train_path(@train)
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_url
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :route_id, :tail)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_edit_number_form.html.erb
<%= form_for [:admin, train], html: { style: "display: none" } do |f| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('common.errors') %></h2>

      <ul>
      <% train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number, class: 'sr-only' %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit t('common.update') %>
  </div>
<% end %>

app/views/admin/trains/_form.html.erb
<div class="row">
  <%= form_for([:admin, train], html: { class: 'form-horizontal col-sm-6', role: 'form' }) do |f| %>
    <% if train.errors.any? %>
      <div id="error_explanation">
        <h2><%= t('common.errors') %></h2>

        <ul>
        <% train.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :number, class: 'col-sm-3 control-label' %>
      <%= f.text_field :number, class: 'col-sm-3 form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :tail, class: 'col-sm-3 control-label' %>
      <%= f.check_box :tail, class: 'col-sm-3' %>
    </div>

    <div class="form-group">
      <%= f.label :route, class: 'col-sm-3 control-label' %>
      <%= f.collection_select :route_id, Route.all, :id, :name, {}, class: 'col-sm-3 form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit "#{@train.new_record? ? t('common.create') : t('common.update')}", class: 'form-control' %>
    </div>
  <% end %>
</div>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="train_number_<%= train.id %>">
      <%= train.number %>
    </div>
    <%= render 'edit_number_form', train: train %>
  </td>
  <td><%= train.route.present? ? link_to(train.route.name, admin_route_path(train.route)) : 'Маршрут не назначен' %></td>
  <td><%= link_to t('common.show'), admin_train_path(train) %></td>
  <td><%= link_to t('common.edit'), '', class: 'edit_train', data: { train_id: train.id } %></td>
  <td><%= link_to t('common.delete'), admin_train_path(train), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', train: @train %>

<%= link_to t('common.show'), admin_train_path(@train), class: 'btn btn-primary' %> |
<%= link_to t('common.back'), admin_trains_path, class: 'btn btn-primary' %>

app/views/admin/trains/index.html.erb
<h3><%= t('.title') %></h3>

<table class='table table-hover'>
  <thead>
    <tr>
      <th><%= t('.number') %></th>
      <th><%= t('.route') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to t('.new_train'), new_admin_train_path, class: 'btn btn-primary' %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', train: @train %>

<%= link_to t('common.back'), admin_trains_path, class: 'btn btn-primary' %>

app/views/admin/trains/show.html.erb
<p>
  <strong><%= t('.train_number_title') %>:</strong>
  <%= @train.number %>
</p>

<p>
  <strong><%= t('.train_route_title') %>:</strong>
  <%= @train.route.present? ? @train.route.name : t('.train_route_unknown')  %>
</p>

<p>
  <strong><%= t('.train_tail_title') %>:</strong>
  <%= @train.tail? ? t('.train_tail_true') : t('.train_tail_false') %>
</p>

<p>
  <strong><%= t('.train_coupe_carriages') %>:</strong>
  <%= @train.coupe_count %>
  <% if @train.coupe.present? %>
    <strong><%= t('.train_top_seats_count') %>:</strong>
    <%= @train.coupe.top_seats %>
    <strong><%= t('.train_bottom_seats_count') %>:</strong>
    <%= @train.coupe.bottom_seats %>
  <% end %>
</p>

<p>
  <strong><%= t('.train_economy_carriages') %>:</strong>
  <%= @train.economy_count %>
  <% if @train.economy.present? %>
    <strong><%= t('.train_top_seats_count') %>:</strong>
    <%= @train.economy.top_seats %>
    <strong><%= t('.train_bottom_seats_count') %>:</strong>
    <%= @train.economy.bottom_seats %>
    <strong><%= t('.train_side_top_seats_count') %>:</strong>
    <%= @train.economy.side_top_seats %>
    <strong><%= t('.train_side_bottom_seats_count') %>:</strong>
    <%= @train.economy.side_bottom_seats %>
  <% end %>
</p>

<p>
  <strong><%= t('.train_business_carriages') %>:</strong>
  <%= @train.business_count %>
  <% if @train.business.present? %>
    <strong><%= t('.train_bottom_seats_count') %>:</strong>
    <%= @train.business.bottom_seats %>
  <% end %>
</p>

<p>
  <strong><%= t('.train_seat_carriages') %>:</strong>
  <%= @train.seat_count %>
  <% if @train.business.present? %>
    <strong><%= t('.train_seats_count') %>:</strong>
    <%= @train.seat.seats %>
  <% end %>
</p>

<% if @train.carriages.present? %>
  <strong><%= t('.carriages_list_title') %>:</strong>
  <% if @train.tail? %>
    <% @train.carriages.desc_position.each do |carriage| %>
      <p>
        <strong><%= carriage.position %>: </strong><%= link_to carriage.number, admin_carriage_path(carriage) %>
      </p>
    <% end %>
  <% else %>
    <% @train.carriages.asc_position.each do |carriage| %>
      <p>
        <strong><%= carriage.position %>: </strong><%= link_to carriage.number, admin_carriage_path(carriage) %>
      </p>
    <% end %>
  <% end %>
<% end %>

<%= link_to t('.new_carriage_button'), new_admin_train_carriage_path(@train), class: 'btn btn-primary' %> |
<%= link_to t('common.edit'), edit_admin_train_path(@train), class: 'btn btn-primary' %> |
<%= link_to t('common.back'), admin_trains_path, class: 'btn btn-primary' %>